/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewLog.java
 *
 * Created on May 11, 2011, 9:44:14 AM
 */

package foldup;
import javax.swing.JDialog;
import java.util.Scanner;
import java.io.FileNotFoundException;
import java.io.File;
import java.util.Random;
/**
 *
 * @author S206_02
 */
public class viewLog extends JDialog {

    /** Creates new form viewLog */
    public viewLog(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logViewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextPane = new javax.swing.JTextPane();
        logLoad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(foldup.FoldUpApp.class).getContext().getResourceMap(viewLog.class);
        logViewLabel.setText(resourceMap.getString("logViewLabel.text")); // NOI18N
        logViewLabel.setName("logViewLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        logTextPane.setName("logTextPane"); // NOI18N
        jScrollPane1.setViewportView(logTextPane);

        logLoad.setText(resourceMap.getString("logLoad.text")); // NOI18N
        logLoad.setName("logLoad"); // NOI18N
        logLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logLoadMouseClicked(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logViewLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(logLoad))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logViewLabel)
                    .addComponent(logLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLoadMouseClicked
        Random rand = new Random();
        int intRand = rand.nextInt(10)+1;
        try {
            Scanner input = new Scanner(new File("log.txt"));
            while(input.hasNext()) {
                logTextPane.setText(logTextPane.getText() + "\n" + input.nextLine());
            }
         }
         catch(FileNotFoundException e) {
         }
        if (intRand == 5) {
            jLabel1.setText("Number five.");
        }
        jLabel1.setText("" + intRand);
    }//GEN-LAST:event_logLoadMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewLog dialog = new viewLog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logLoad;
    private javax.swing.JTextPane logTextPane;
    private javax.swing.JLabel logViewLabel;
    // End of variables declaration//GEN-END:variables

}
